trigger:
  - main
  
pool:
  vmImage: ubuntu-latest

jobs:
- job: createRG
  displayName: Create Resource Group
  steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: '$(armConnection)'
      scriptType: 'bash'
      scriptLocation: 'scriptPath'
      scriptPath: './scripts/1.rg-create.sh'
      arguments: '-r arm-private-deployment -l northeurope'
      workingDirectory: './templates'
      failOnStandardError: true

- job: createTS
  displayName: Create Azure Template Spec
  dependsOn: createRG
  steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: '$(armConnection)'
      scriptType: 'bash'
      scriptLocation: 'scriptPath'
      scriptPath: './scripts/2.ts-create.sh'
      arguments: '-r arm-private-deployment -l northeurope -v "0.1" -t "azuredeploy.json" -n arm-private-deployment-ts'
      workingDirectory: './templates'

- job: deployTS
  displayName: Deploy Azure Template Spec
  dependsOn: createTS
  steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: '$(armConnection)'
      scriptType: 'bash'
      scriptLocation: 'scriptPath'
      scriptPath: './scripts/3.deploy-ts.sh'
      arguments: '-r arm-private-deployment -l northeurope -n arm-private-deployment-ts -v "0.1"'
      workingDirectory: './templates'
      failOnStandardError: true