name: arm-private-deployment

on:
  workflow_dispatch:

jobs:
  arm-private-deployment:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: az login
      run: |
        az login --service-principal \
          -u ${{ secrets.SP_APP_ID }} \
          -p ${{ secrets.SP_PASSWORD }}

    - name: az account set
      run: az account set -s ${{ secrets.SUBSCRIPTION_ID }}

    - name: validate subscription selection
      run: |
          currentsub=$(az account show --query id --output tsv)
          if [ ! "$currentsub" = "${{ secrets.SUBSCRIPTION_ID }}" ]; then
            echo -e "** Unable to select requested subscription.\nPlease make sure the Service Principal has access to this subscription - exiting **"
            exit 1
          fi

    - name: Create RG for Template Specs
      run: |
        ./scripts/1.rg-create.sh \
          -r template-specs \
          -l northeurope

    - name: Created Azure Template Spec
      run: |
        ./scripts/2.ts-create.sh \
          -r template-specs \
          -l northeurope \
          -v 0.1 \
          -t azuredeploy.json \
          -n arm-private-deployment-ts

    - name: Deploy Azure Template Spec
      run: |
        ./scripts/3.deploy-ts.sh \
          -r arm-private-deployment \
          -l northeurope \
          -v 0.1 \
          -n arm-private-deployment-ts \
          -t template-specs 

