name: arm-private-deployment

on:
  workflow_dispatch:

env:
  LOCATION: northeurope
  TEMPLATE_SPEC_RESOURCE_GROUP: template-specs
  TEMPLATE_SPEC_VERSION: "0.1"
  TEMPLATE_SPEC_NAME: arm-private-deployment-ts
  DEPLOY_RESOURCE_GROUP: arm-private-deployment

jobs:
  arm-private-deployment:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Log in with Azure
      uses: azure/login@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'

    - name: Create RG for Template Specs
      run: |
        ./scripts/1.rg-create.sh \
          -r ${{ env.TEMPLATE_SPEC_RESOURCE_GROUP }} \
          -l ${{ env.LOCATION }}

    - name: Created Azure Template Spec
      run: |
        ./scripts/2.ts-create.sh \
          -r ${{ env.TEMPLATE_SPEC_RESOURCE_GROUP }} \
          -l ${{ env.LOCATION }} \
          -v ${{ env.TEMPLATE_SPEC_VERSION }} \
          -t ./templates/azuredeploy.json \
          -n ${{ env.TEMPLATE_SPEC_NAME}}

    - name: Deploy Azure Template Spec
      run: |
        ./scripts/3.deploy-ts.sh \
          -r ${{ env.DEPLOY_RESOURCE_GROUP }} \
          -l ${{ env.LOCATION }} \
          -v ${{ env.TEMPLATE_SPEC_VERSION }} \
          -n ${{ env.TEMPLATE_SPEC_NAME}} \
          -t ${{ env.TEMPLATE_SPEC_RESOURCE_GROUP }}

