name: arm-private-deployment

on:
  workflow_dispatch:

jobs:
  arm-private-deployment:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Log in with Azure
      uses: azure/login@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'

    - name: Create RG for Template Specs
      run: |
        ./scripts/1.rg-create.sh \
          -r template-specs \
          -l northeurope

    - name: Created Azure Template Spec
      run: |
        ./scripts/2.ts-create.sh \
          -r template-specs \
          -l northeurope \
          -v 0.1 \
          -t ./templates/azuredeploy.json \
          -n arm-private-deployment-ts

    - name: Deploy Azure Template Spec
      run: |
        ./scripts/3.deploy-ts.sh \
          -r arm-private-deployment \
          -l northeurope \
          -v 0.1 \
          -n arm-private-deployment-ts \
          -t template-specs

